### ISSUE TITLE
error trying to build osm2pgsql

### ISSUE THREAD

**Issue by haroldship** [geo-data/openstreetmap-tiles-docker#18]
I'm pretty new to docker. I hand-built an OSM tile server and want to create a docker image, hopefully based on yours, but with some modifications.

I git-cloned and tried to build the image. I get many warnings, but ultimately the build fails on this error:

> Step 10 : RUN cd /tmp && git clone git://github.com/openstreetmap/osm2pgsql.git
>  ---> Running in e21dc5361327
> Cloning into 'osm2pgsql'...
>  ---> 93cdcd7b258e
> Removing intermediate container e21dc5361327
> Step 11 : RUN cd /tmp/osm2pgsql &&     ./autogen.sh &&     ./configure &&     make && make install
>  ---> Running in 4c82958004c8
> /bin/sh: 1: ./autogen.sh: not found
> The command '/bin/sh -c cd /tmp/osm2pgsql &&     ./autogen.sh &&     ./configure &&     make && make install' returned a non-zero code: 127

There appears to be an image in `docker images`

**Comment by erikj** [comment]
it looks like the build process for `osm2pgsql` changed w/ this commit: https://github.com/openstreetmap/osm2pgsql/commit/b0ef2692ec33dc1a9cf391027aec16adf6a175fa#diff-04c6e90faac2675aa89e2176d2eec7d8

to resolve the issue, you can either update your `Dockerfile` to
- checkout `osm2pgsql` @ a commit prior to that one
- or build via `osm2pgsql`'s current steps:
  - `mkdir build && cd build && cmake .. && ./configure && make && make install'`
  - https://github.com/openstreetmap/osm2pgsql/blob/master/README.md#building

**Comment by haroldship** [comment]
Thanks that worked for the build. However, when I try to import I get the following error:

> Importing /data/import.osm into his
> 800
> osm2pgsql SVN version 0.89.0-dev (64 bit id space)
> 
> Osm2pgsql failed due to ERROR: Couldn't open style file './default.style': No such file or directory
> ^C**\* Shutting down /usr/local/sbin/run (PID 95)...

**Comment by erikj** [comment]
> > Osm2pgsql failed due to ERROR: Couldn't open style file './default.style': No such file or directory
> > ^C**\* Shutting down /usr/local/sbin/run (PID 95)...

That looks like it's related to openstreetmap/osm2pgsql#515: _New master build needs specifying default style_

You should be able to get around it by checking out a prior commit (per above) or adding the specified flag to `import()`'s `osm2pgsql` command:

``` sh
--style /usr/local/share/osm2pgsql/default.style 
```

https://github.com/geo-data/openstreetmap-tiles-docker/blob/master/run.sh#L81

**Comment by haroldship** [comment]
Thank you again @erikj. However, I had to make some other changes in order to get things working (they are now). Would you like the changes?

**Comment by erikj** [comment]
@haroldship yeah, that would be great, thanks!

and you're welcome! :)

**Comment by haroldship** [comment]
sent a pull request
